### PR TITLE
Updated link to icon set

### PR DESCRIPTION
**Pull request by jacobszpz**
Updated link for custom icons which was no longer valid.

### CODE REVIEW

**Comment by Alhadis** [comment]
Nice catch. Thanks!

**Comment by jacobszpz** [comment]
Hey, I have a question. Where was the PDF icon taken from? I looked through icons.less but I couldn't find it. Thanks.

**Comment by Alhadis** [comment]
It's actually part of Atom's built-in icon set, [Octicons](https://primer.style/octicons/).

**Comment by jacobszpz** [comment]
I looked through all of them and I couldn't find it, unfortunately. It looks like this
in atom.

**Comment by jacobszpz** [comment]
So I managed to find the icon in a previous download I had of Octicons, which is great. What's interesting is that the pdf icon seems to be missing in the link you provided. But anyway, thanks a lot.

**Comment by Alhadis** [comment]
Atom uses an outdated version of Octicons. It sounds like they dropped the PDF icon at some point (which might explain why they're still using the older one).

**Pull request merged**
