### PR TITLE
Fix performance hole

### PR DESCRIPTION
**Pull request by aminya**
This part of the code takes 300ms for its execution! This is not what people want in the production code.
You can measure it by 
```js
const t1 = window.performance.now()
// code ...
console.log(window.performance.now()-t1)
```

# Before
image
image

# After
image
image

### CODE REVIEW

**Comment by Alhadis** [comment]
Thanks for watching so closely. Unfortunately, you misinterpreted what's meant by "tests". I meant *literal* test-files in a user's project that contain interpreter directives:

Figure 1

See daa9906 and #812 for background and rationale.

**Comment by aminya** [comment]
300 ms is a lot. My whole Atom loads in 400ms, and this is taking about that time!

If this is just a feature: it should be disabled by default and add an `atom.config` to let the user enable it, if they want to.

**Comment by Alhadis** [comment]
> Remember that JS/JSON parser of V8 is written in C++ and is super fast, and in contrast, searching through the whole icon set is very expensive and slow.

You really need to read up on what you're talking about... 😜 Ignition (V8's bytecode interpreter) and TurboFan are [more complex](https://docs.google.com/presentation/d/1chhN90uB8yPaIhx_h2M3lPyxPgdPmkADqSNAoXYQiVE/edit#slide=id.g1ba5e472dd_0_137) than what you're describing. It's not a straight lex-and-parse at whatsoever.

**Comment by aminya** [comment]
On master, this is fixed now. Making the map offline was the best move.

**Pull request closed without merging**
