### PR TITLE
Add support for license-PREFIX

### PR DESCRIPTION
**Pull request by spenserblack**
There are [+19.2k files that follow the format `license-PREFIX`](https://github.com/search?q=path%3A%2F%28%5E%7C%5C%2F%29LICENSE-%28%5Cw%5B%5Cw%5Cd%5D*%29%24%2F&type=code).

[+13k of these are `LICENSE-MIT` or `LICENSE-APACHE`](https://github.com/search?q=path%3A%2F%28%5E%7C%5C%2F%29LICENSE-%28MIT%7CAPACHE%29%24%2F&type=code), which is a very common dual-license in the Rust ecosystem.

Right now this change change has indefinite variations, but, that this could be limited to two variations and satisfy the majority, perhaps this proposed change should be simplified to only check these two prefixes.

## To do

If this is merged as-is with indefinite variations, I suppose I'll have to also add some of the most common as manual fixes to the vscode repository :slightly_smiling_face:

### CODE REVIEW

**Comment by spenserblack** [comment]
Oops, I should have read the regex more clearly and tested it out first. It already does match these files, sorry.

**Comment by Alhadis** [comment]
@spenserblack Haha, all good mate. The reason you're not seeing this in VS Code is because of the inherit limitations of its icon-themes: it can only map icons by file-extension or unabridged filename. 😞

**Comment by spenserblack** [comment]
Thanks! I'll do some research into the most popular `-FOO` suffixes and make a PR to the vscode repo to add them to the "missing filenames" file if that sounds good. If I understood correctly, that should add the icons to `LICENSE-MIT`, `LICENSE-APACHE`, etc. if they're hardcoded in that file, right?

No rush, but speaking about VS Code, is there a rough ETA for the next release? This is absolutely the prettiest icon theme IMO :slightly_smiling_face: The more files with icons, the prettier :laughing:

**Comment by Alhadis** [comment]
> No rush, but speaking about VS Code, is there a rough ETA for the next release?

Damn, I thought I already cut a release. 🤔 So these changes have been sitting here for over a year… completely unpublished. 😅

Let me see what I can do.

**Comment by Alhadis** [comment]
Currently trying to figure out what the hell's going on over at <samp>marketplace.visualstudio.com</samp>. 😖 This error message is—in [classic Microsoft fashion](https://pbs.twimg.com/media/E4mkrRWVUAISxzi.jpg)—equal parts frustrating and uninformative.

Figure 1

**Comment by Alhadis** [comment]
Right. After several days of hair-pulling and loud profanity, I figured out what was wrong: turns out I wasn't including `LICENSE.md` in the packaged `*.vsix` (something which wasn't a problem _before_, but was clearly introduced as a new headache in some new VSCode release).

**Comment by spenserblack** [comment]
Awesome, thanks!

**Comment by Alhadis** [comment]
No problem! 😀 Again, I'm sorry the release took _over a fucking year._ This should give you an indication as to how chaotic my workspace is at the moment… 😞

**Pull request closed without merging**
