### PR TITLE
.prettierignore file support

### LINKED ISSUE #718: Support for .prettierignore file
What do you think about using the Prettier logo (or a faded version like ESLint) for `.prettierignore` files?

screenshot

### PR DESCRIPTION
**Pull request by ahmedkaba**
Thanks for cool project! 😎
This pr closes #718

### CODE REVIEW

**Comment by Alhadis** [comment]
Thanks!

**Comment by cbovis** [comment]
@Alhadis can we get a release put together with this included? Bugs me every time I see it 😝

**Comment by Alhadis** [comment]
Sorry mate, been trying to tie up some loose ends on major projects which are nearly finished, so I'm able to resume work on this package undistracted. =)

Will cut a release shortly. 😉

**Comment by cbovis** [comment]
Legend, thanks John!

**Pull request merged**
