### PR TITLE
Switch ESLint colours

### PR DESCRIPTION
**Pull request by DeadlyMissile**
cc @Alhadis

### CODE REVIEW

**Comment by Alhadis** [comment]
What's the rationale for this change, exactly?

**Comment by DeadlyMissile** [comment]
I thought you [agreed](https://github.com/file-icons/atom/pull/884#issuecomment-1636442777) on this change?

**Comment by Alhadis** [comment]
My bad, I misread your comment and thought you were asking for confirmation on whether `eslint.config.js` should share the same colour as `.eslintrc.*` files.

Generally, we try to avoid making purely-subjective changes like colour swaps unless there's an easily-justified reason to do so. Users can always change an icon's colour with their stylesheets if they so choose (and such customisations are encouraged). I'm aware this functionality isn't possible with the VS Code extension… yet. But hopefully that'll change some day.

**Comment by DeadlyMissile** [comment]
@Alhadis But I don’t understand why the important files (eslint.config.js or .eslintrc) have a lighter color than the less important ones (cache or ignore). My understanding is that brighter colors usually indicate something of higher importance.

**Comment by DeadlyMissile** [comment]
In fact, I don’t think I have ever used .eslintcache or ignore.

**Comment by Alhadis** [comment]
> My understanding is that brighter colors usually indicate something of higher importance.

Generally, that's not the case. Brighter colours tend to be picked first for the most prominent and common filetypes, with darker shades picked later. Sometimes it's the opposite, such as when a logo's official branding uses darker colours. Other times, the decision is completely arbitrary, such as when differentiating very different filetypes that share a generic-looking icon (e.g., text files, data files, INI files, etc).

**Comment by DeadlyMissile** [comment]
I would have preferred the medium purple for the main config files since they are used often. However since you disagree I will just close this PR then.

**Pull request closed without merging**
